/**
 * Created by HP-Laptop on 17-Aug-16.
 */
import java.util.ArrayList;
import java.util.Collections;
public class Program {

                                                        // random numbers generated by program
    private void extragereNumereProgram(){
        ArrayList<Integer> list = new ArrayList<Integer>();
        for (int i=1; i<=49; i++) {
            list.add(new Integer(i));
        }
        Collections.shuffle(list);


        ArrayList<Integer> listaNumereExtraseProgram = new ArrayList<Integer>();
        for (int i=0; i<6; i++) {
            listaNumereExtraseProgram.add(list.get(i));
        }
    }

    public void extragereProgram (){
        extragereNumereProgram();
    }


    public void extragereNumereUser(String inputUser){

        int [] numereUtilizator = new int [6];




    }


}